---
- hosts: all
  vars_prompt:
  - name: "nameofmachine"
    prompt: "Enter of name machine"
    private: no
  - name: "type"
    prompt: "Enter of type of server"
    private: no
  tasks:

    - name: Rename
      raw: hostname {{ nameofmachine }}
      
    - name: Install httpd
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - httpd
      when: type == "web"

    - name: Install httpd
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - vsftpd
      when: type == "ftp"
